#python plotFromTree.py -i ../../VHbbAnalysis/V23_Wlnu_CR_July1.0/output_data.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlydata.dat -o output_data.root
#python plotFromTree.py -i ../../VHbbAnalysis/V23_Wlnu_CR_July1.0/output_mc.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -o output_mc.root -w 'weight*(1.0/1.0)*(12.89/12.89)**(2.28/9.24)'
#python plotFromTree.py -i ../../VHbbAnalysis/V23_Wlnu_CR_July1.0/output_ttpowheg.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlyttpowheg.dat -o output_ttpow.root -w 'weight*(1.0/1.0)*(12.89/12.89)**(2.28/9.24)'
#python plotFromTree.py -i /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_CR_March13_data_reminiaod/output_data.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlydata.dat -o output_data.root
#python plotFromTree.py -i /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_CR_March13_NLOWJets/output_wjetsnlo_2.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlynlowjets.dat -o output_nlowjets.root -w 'weight*bTagWeightMoriondCMVA*(1./CS_SF)'
python plotFromTree.py -i /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_CR_April6_data/output_data.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlydata.dat -o output_data.root
#python plotFromTree.py -i /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_CR_April6_v2_data/output_data.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlydata.dat -o output_data.root
#python plotFromTree.py -i /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_CR_March13_TTMadNoSys/output_ttmadgraph_3.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlyttmad.dat -o output_ttpow.root -w 'weight*(1./CS_SF)*bTagWeightMoriondCMVA*VPtCorrFactorSplit3'
####python plotFromTree.py -f /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_CR_April6_QCD/haddjobs/ -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlyqcd.dat -o output_qcd.root -w 'weight*(1./CS_SF)*bTagWeightMoriondCMVA*VPtCorrFactorSplit3'
python plotFromTree.py -f /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_CR_April6_v2/haddjobs/ -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlyvz.dat -o output_vz.root -w 'weight*(1./CS_SF)*bTagWeightMoriondCMVA*VPtCorrFactorSplit3'
python plotFromTree.py -f /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_CR_April6_v2/haddjobs/ -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -o output_mc.root -w 'weight*(1./CS_SF)*bTagWeightMoriondCMVA*VPtCorrFactorSplit3'
python plotFromTree.py -f /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_CR_April6_v2/haddjobs/ -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlyttpowheg.dat -o output_ttpow.root -w 'weight*(1./CS_SF)*bTagWeightMoriondCMVA*VPtCorrFactorSplit3'
python plotFromTree.py -f /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_CR_April6_v2/haddjobs/ -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlysignal.dat -o output_signal.root -w 'weight*(1./CS_SF)*bTagWeightMoriondCMVA*VPtCorrFactorSplit3'
hadd -f output.root output_mc.root output_data.root output_ttpow.root output_signal.root output_vz.root output_qcd.root
#hadd -f output.root output_mc.root output_data.root output_ttpow.root output_signal.root
#hadd -f output.root output_mc.root output_data.root output_ttpow.root output_signal.root output_nlowjets.root
#python plotFromTree.py -i ../../V24_Wln_CR_Oct13_v2/output_data.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlydata.dat -o output_data.root
#python plotFromTree.py -i ../../V24_Wln_CR_Oct13_v2/output_mc.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -o output_mc.root 
#python plotFromTree.py -i ../../V24_Wln_CR_Oct13_v2/output_ttpowheg.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlyttpowheg.dat -o output_ttpow.root 
#python plotFromTree.py -i ../../V24_Wln_CR_Oct13_v2/output_signal.root -P plotvariables_CS.dat -C categories_CS.dat -S selection_CS.dat -I inputfiles_onlysignal.dat -o output_signal.root
#hadd -f output.root output_mc.root output_data.root output_ttpow.root output_signal.root
