python plotFromTree.py -i /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_SR_April6_data/output_data.root -P plotvariables.dat -C categories.dat -S selection.dat -I inputfiles_onlydata.dat -o output_data.root
####python plotFromTree.py -f /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_SR_April6_QCD/haddjobs/ -P plotvariables.dat -C categories.dat -S selection.dat -I inputfiles_onlyqcd.dat -o output_qcd.root -w 'weight*(1./CS_SF)*bTagWeightMoriondCMVA*VPtCorrFactorSplit3'
python plotFromTree.py -f /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_SR_April6/haddjobs/ -P plotvariables.dat -C categories.dat -S selection.dat -I inputfiles_onlyvz.dat -o output_vz.root -w 'weight*(1./CS_SF)*bTagWeightMoriondCMVA*VPtCorrFactorSplit3'
python plotFromTree.py -f /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_SR_April6/haddjobs/ -P plotvariables.dat -C categories.dat -S selection.dat -o output_mc.root -w 'weight*(1./CS_SF)*bTagWeightMoriondCMVA*VPtCorrFactorSplit3'
python plotFromTree.py -f /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_SR_April6/haddjobs/ -P plotvariables.dat -C categories.dat -S selection.dat -I inputfiles_onlyttpowheg.dat -o output_ttpow.root -w 'weight*(1./CS_SF)*bTagWeightMoriondCMVA*VPtCorrFactorSplit3'
python plotFromTree.py -f /eos/uscms/store/user/sbc01/VHbbAnalysisNtuples/V25_Wlnu_SR_April6/haddjobs/ -P plotvariables.dat -C categories.dat -S selection.dat -I inputfiles_onlysignal.dat -o output_signal.root -w 'weight*(1./CS_SF)*bTagWeightMoriondCMVA*VPtCorrFactorSplit3*VHCorrFactor'
hadd -f output.root output_mc.root output_data.root output_ttpow.root output_signal.root output_vz.root output_qcd.root
#hadd -f output.root output_mc.root output_data.root output_ttpow.root output_signal.root
#hadd -f output.root output_mc.root output_data.root output_ttpow.root output_signal.root output_nlowjets.root
